// /**
//  * es6 modules and imports
//  */
// import sayHello from './hello';
// sayHello('Augustine');
//
// /**
//  * require style imports
//  */

const $ = require('jquery');
const {getMovies, addMovie, editMovie, deleteMovie} = require('./api.js');
// const {getMovies, addMovies, editMovies, deleteMovies} = require('./api.js');


// "loading..." Placeholder
$("tbody").html('<p>loading...</p>');

// DISPLAY MOVIES LIST/TABLE
// const movies = () =>
getMovies().then((movies) => {
    updateMovies(movies);
}).catch((error) => {
    alert('Oh no! Something went wrong.\nCheck the console for details.');
    console.log(error);
});
// movies();
// UPDATE MOVIES (DISPLAY LIST/TABLE)
const updateMovies = movies => {
    // console.log('Here are all the movies:');
    let movieList = '';
    movies.forEach(({title, rating, id, genre}) => {
        console.log(`id#${id} ${title} rating: ${rating} genre: ${genre}`);
        movieList += `<tr class="d-flex flex-nowrap">
            <!--added d-flex justify content center to line up with table head-->
            <td class="col-5 d-flex justify-content-center">${title}</td>
            <!--added 'stars' to show with number rating-->
            <td class="col-2 d-flex justify-content-center">${rating} stars</td>
            <td class="col-2 d-flex justify-content-center">${genre}</td>
            <td><button class="col btn btn-outline-info" id="edit">edit</td>
            <td><button type='submit' data-dbid='${id}' class="col btn btn-outline-danger delete-btn">delete</button></td>
            </tr>`;

    });
    $('tbody').html(movieList);
    // console.log(movieList);
}



// ADD MOVIE
$('#add-movie-btn').click(function (event) {
    event.preventDefault();
    // console.log("test");
    let addTitle = $('#title').val();
    let addRating = $('#rating').val();
    let addGenre = $('#genre').val();
    if (addTitle === "") {
        alert("Enter a movie title");
        // add a function to check if it already exists
    } else {
        const movie = {
            'title': addTitle,
            'rating': addRating,
            'genre': addGenre
        };
        addMovie(movie).then();
        // the id is autogenerated
        getMovies().then((movies) => {
            updateMovies(movies);
        });
        $("#add-movie").trigger("reset");
    }
});

//edit existing movie
// $('#edit').click(function(e){
//     e.preventDefault();
//     console.log($('#edit').serializeArray())
// })





//delete existing movie
$('tbody').on('click', '.delete-btn', function(e) {

    // this.children('.btn-delete');
    const movieId = $(e.target).data('dbid');
    console.log("this is the id " + movieId);

    getMovies().then((movies) => {
        // movies.forEach(({title,rating,id}) => {
        //     if(movieId === id){
        const movie = movies.filter((curr) => curr.id === movieId)[0];
        deleteMovie(movie).then()
        getMovies().then((movies) => {
            updateMovies(movies);
        });
        //         }
        //     })
        //
        // })
    });
    //
    // const movie = getMovies().filter((curr) => curr.id === id)[0];
    // deleteMovie(movie.id).then(updateMovies)
});
