// /**
//  * es6 modules and imports
//  */
// import sayHello from './hello';
// sayHello('Augustine');
//
// /**
//  * require style imports
//  */

const $ = require('jquery');
const {getMovies, addMovie} = require('./api.js');
// const {getMovies, addMovies, editMovies, deleteMovies} = require('./api.js');

// "loading..." Placeholder
$("tbody").html('<p>loading...</p>');

// DISPLAY MOVIES LIST/TABLE
getMovies().then((movies) => {
    updateMovies(movies);
}).catch((error) => {
    alert('Oh no! Something went wrong.\nCheck the console for details.');
    console.log(error);
});

// UPDATE MOVIES (DISPLAY LIST/TABLE)
const updateMovies = movies => {
    // console.log('Here are all the movies:');
    let movieList = '';
    movies.forEach(({title, rating, id, genre}) => {
        console.log(`id#${id} ${title} rating: ${rating} genre: ${genre}`);
        movieList += `<tr class="d-flex">
            <td class="col-1">${id}</td>
            <td class="col-5">${title}</td>
            <td class="col-3">${rating}</td>
            <td class="col-3">${genre}</td></tr>`;
    });
    $('tbody').html(movieList);
    // console.log(movieList);
}

// ADD MOVIE
$('#add-movie-btn').click(function (event) {
    event.preventDefault();
    // console.log("test");
    let addTitle = $('#title').val();
    let addRating = $('#rating').val();
    let addGenre = $('#genre').val();
    if (addTitle === "") {
        alert("Enter a movie title");
        // add a function to check if it already exists
    } else {
        const movie = {
            'title': addTitle,
            'rating': addRating,
            'genre': addGenre
        };
        addMovie(movie);
        // the id is autogenerated
        getMovies().then((movies) => {
            updateMovies(movies);
        });
        $("#add-movie").trigger("reset");
    }
});
