// /**
//  * es6 modules and imports
//  */
// import sayHello from './hello';
// sayHello('Augustine');
//
// /**
//  * require style imports
//  */

const $ = require('jquery');
const {getMovies, addMovie, editMovie, deleteMovie} = require('./api.js');

// "loading..." Placeholder
$("tbody").html('<p>loading...</p>');


// DISPLAY MOVIES LIST/TABLE
getMovies().then((movies) => {
    displayMovies(movies);
}).catch((error) => {
    alert('Oh no! Something went wrong.\nCheck the console for details.');
    console.log(error);
});


// UPDATE MOVIES LIST/TABLE
const displayMovies = movies => {
    let movieList = '';
    movies.forEach(({title, rating, id, genre}) => {
        console.log(`id#${id} ${title} rating: ${rating} genre: ${genre}`);
        movieList += `<tr class="d-flex flex-nowrap">
            <!--added d-flex justify content center to line up with table head-->
            <td class="col-5 d-flex justify-content-center">
                <span class="noedit">${title}</span>
                <input class="edit title"/>
            </td>
            <!--added 'stars' to show with number rating-->
            <td class="col-2 d-flex justify-content-center">
                <span class="noedit">${rating}<span>
                <input class="edit rating"/>
            </td>
            <td class="col-2 d-flex justify-content-center">
                <span class="noedit">${genre}</span>
                <input class="edit genre"/>
            </td>
            <td><button type='submit' data-dbid='${id}' data-title='${title}' data-rating='${rating}' data-genre='${genre}' class="col btn btn-sm btn-outline-info edit-btn">Edit</button>
                <button type="submit" class="edit btn btn-sm btn-outline-success save-btn">Save</button>
                <button type="submit" class="edit btn btn-sm btn-outline-secondary cancel-btn">Cancel</button></td>
            <td><button type='submit' data-dbid='${id}' class="col btn btn-sm btn-outline-danger delete-btn">Delete</button></td>
            </td>
            </tr>`;
        // Tried using icons in place of and with button text, but it broke the delete functionality...
        // <i class="fas fa-edit"></i>
        // <i class="far fa-minus-square"></i>

    });
    $('tbody').html(movieList);
}


// ADD MOVIE
$('#add-movie-btn').click(function (event) {
    event.preventDefault();
    let addTitle = $('#title').val();
    let addRating = $('#rating').val();
    let addGenre = $('#genre').val();
    if (addTitle === "" || addRating === "default" || addGenre === "default") {
        alert("Enter the movie title and select a genre & rating!");
        // todo: add a check to see if the movie already exists
    } else {
        const movie = {
            'title': addTitle,
            'rating': addRating,
            'genre': addGenre
        };
        addMovie(movie).then();
        // the id is autogenerated
        getMovies().then((movies) => {
            displayMovies(movies);
        });
        $("#add-movie").trigger("reset");
    }
});

// EDIT MOVIE
// $('#edit').click(function(e){
//     e.preventDefault();
//     console.log($('#edit').serializeArray())
// })
$('tbody').on('click', '.edit-btn', function (e) {
    let movieId = $(e.target).data('dbid');
    let title = $(e.target).data('title');
    let rating = $(e.target).data('rating');
    let genre = $(e.target).data('genre');
    console.log("Edit movie info: " + movieId, title, rating, genre);
    // $('tr').addClass('edit');
});

$('tbody').on('click', '.cancel-btn', function (e) {
    $(this).closest('tr').removeClass('edit');
});

$('tbody').on('click', '.save-btn', function (e) {
    let $tr = $(this).closest('tr');
    let movie = {
    title: $tr.find('input.title').val(),
    rating: $tr.find('input.rating').val(),
    genre: $tr.find('input.genre').val(),
    id: movieId
    };

    if (movie.title === "" || movie.rating === "" || movie.genre === "") {
        alert("Check for missing values!");
        // todo: add a check to see if the movie already exists
    } else {
        editMovie(movie).then()
        getMovies().then((movies) => {
            displayMovies(movies);
        });
    }
});

// DELETE MOVIE
$('tbody').on('click', '.delete-btn', function (e) {

    // this.children('.btn-delete');
    const movieId = $(e.target).data('dbid');
    console.log("this is the id " + movieId);

    getMovies().then((movies) => {
        // movies.forEach(({title,rating,id}) => {
        //     if(movieId === id){
        const movie = movies.filter((curr) => curr.id === movieId)[0];
        deleteMovie(movie).then()
        getMovies().then((movies) => {
            displayMovies(movies);
        });
        //         }
        //     })
        //
        // })
    });
    //
    // const movie = getMovies().filter((curr) => curr.id === id)[0];
    // deleteMovie(movie.id).then(updateMovies)
});
